require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/scm/git"
require "capistrano/rails/migrations"
require "capistrano/rails/assets"
require "capistrano/rbenv"
require "capistrano/bundler"

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
